<a href="https://colab.research.google.com/github/PrasadRaoJammuna/ML-Classes/blob/master/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import style
style.use('fivethirtyeight')
  
import warnings
warnings.filterwarnings('ignore')
  
%matplotlib inline

In [0]:
# GRADED
# 
# (a) Using a for loop, iterate through the list x
# and print an item if its divisible by 2 and less than 6
# (b) Using a for loop, iterate through the dictionary y
# and print a single string of the form "company, ceo"
# e.g. "CEO: Apple, Name: Tim Cook" will be the third entry
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {
    'Satya Nadella': 'Microsoft',
    'Jeff Bezos': 'Amazon',
    'Tim Cook': 'Apple'
}

## **Solutions**

In [0]:
#a
for i in x:
  if i<6 and i%2==0:
    print(i)
    
print()

for key,values in y.items():
  print(f'Name:{key}',f' Company:{values}')

2
4

Name:Satya Nadella  Company:Microsoft
Name:Jeff Bezos  Company:Amazon
Name:Tim Cook  Company:Apple


In [0]:

# GRADED
# Provided below are functions that are completely defined (add_numbers),
# partially defined (sub_numbers) and not defined (mult_numbers)
# (a) Complete sub_numbers so that it return difference of two numbers
# (b) Write a function called mult_numbers to multiply two numbers

def add_numbers(a, b):
    result = a + b
    return result

def sub_numbers(a, b):
    # Write code to return sum of a and b
    result =  a-b #Replace 0 with your code
    return result

def mult_numbers(a, b):
    result = a*b
    return result
# Uncomment the following when you have done the exercise
# a^2-b^2 = (a+b)*(a-b)
# e.g 5^2 - 4^2 = (5+4)(5-4) = 9
# print(mult_numbers(add_numbers(5,4), sub_numbers(5,4)))
# Should print 9

In [0]:
print(mult_numbers(add_numbers(5,4), sub_numbers(5,4)))

9


In [0]:
### GRADED
# (a) Determine the shape, number of dimensions and type of 
# elements in the numpy array arr
# (b) Determine the sum of elements in arr
# (c) Determine the mean of elements in arr
# (d) Create an array of the same shape as arr but filled with zeros
# (e) Create an array of the same shape as arr but filled with ones
# (f) Create an array of the same shape as arr but where all elements are squared values
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot
arr = np.arange(15).reshape(3, 5)

In [0]:
# elements in the numpy array arr
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
#(a) Determine the shape, number of dimensions and type of 
print(arr.shape)
print(arr.ndim)
print(type(arr))

(3, 5)
2
<class 'numpy.ndarray'>


In [0]:
# (b) Determine the sum of elements in arr
arr.sum()

105

In [0]:
# (c) Determine the mean of elements in arr
arr.mean()

7.0

In [0]:
# (d) Create an array of the same shape as arr but filled with zeros
np.zeros(arr.shape)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
# (e) Create an array of the same shape as arr but filled with ones
np.ones(arr.shape)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [0]:
# (f) Create an array of the same shape as arr but where all elements are squared values
arr**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [0]:
# (g) Create an array result of shape 3*3 resulting from multiplication of arr with transpose(arr). Hint: use np.dot


In [0]:
### GRADED
# The following piece of code creates a DataFrame 
# (a) Determine the shape of the dataframe
# (b) Print out all the columns of the dataframe
# (c) Print the 3rd element of the dataframe
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head(10) #prints the first 10 rows

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa
7           5.0          3.4           1.5          0.2  setosa
8           4.4          2.9           1.4          0.2  setosa
9           4.9          3.1           1.5          0.1  setosa

In [0]:
# (a) Determine the shape of the dataframe
df.shape

(150, 5)

In [0]:
# (b) Print out all the columns of the dataframe
print('Columns: ',df.columns)
print(15*'==')

# (c) Print the 3rd element of the dataframe
print('3rd Element\n',df.loc[3])
print(15*'==')

Columns:  Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')
3rd Element
 sepal_length       4.6
sepal_width        3.1
petal_length       1.5
petal_width        0.2
species         setosa
Name: 3, dtype: object


In [0]:
# (d) Find the average of 'petal_width' where species is 'virginica'
# (e) Find the maximum of 'sepal_width' where species is 'setosa'
# (f): What is the average value of sepal_length
# (g): What is the maximum value of sepal_width
# (h): What is the minimum value of petal_width

df.groupby('species').agg(['min','max','mean'])

sepal_length             sepal_width  ... petal_length petal_width            
                    min  max   mean         min  ...         mean         min  max   mean
species                                          ...                                     
setosa              4.3  5.8  5.006         2.3  ...        1.462         0.1  0.6  0.246
versicolor          4.9  7.0  5.936         2.0  ...        4.260         1.0  1.8  1.326
virginica           4.9  7.9  6.588         2.2  ...        5.552         1.4  2.5  2.026

[3 rows x 12 columns]