<a href="https://colab.research.google.com/github/PrasadRaoJammuna/ML-Classes/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
l =[1,2,3,4,5]
a =np.array(l)
a

array([1, 2, 3, 4, 5])

In [0]:
a*2

array([ 2,  4,  6,  8, 10])

In [0]:
a.shape

(5,)

In [0]:
x =np.array(range(100))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
index = np.array(range(10))*2
index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
x[index]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
a.shape

(5,)

In [0]:
a =np.array([[1.0,2,3],[4,5,6]])
a.shape

(2, 3)

In [0]:
np.zeros_like(a) # It create the array as 'a' with zeros
# it take the exact values in 'a'..#float or #int

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
np.empty(2)

array([-9.25596313e+061,  2.42818443e-319])

In [0]:
a = np.array([[1,2,3,4]])
b= np.array([[3,5,6,7]])

a*b

array([[ 3, 10, 18, 28]])

In [0]:
a+b

array([[ 4,  7,  9, 11]])

In [0]:
a-b

array([[-2, -3, -3, -3]])

In [0]:
a*2

array([[2, 4, 6, 8]])

In [0]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [0]:
a=np.array([[1]])
a

array([[1]])

In [0]:
d =a.T

In [0]:
d.shape

(1, 1)

In [0]:
a.shape

(1, 1)

In [0]:
np.argmin(a)

0

In [0]:
np.argmax(a)
# it is used for finding max value position in that array

# for help use np.argmax?

0

In [0]:
np.argmin(a)

0

In [0]:
a = np.array([range(10)])
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [0]:
a >3

array([[False, False, False, False,  True,  True,  True,  True,  True,
         True]])

In [1]:
pip install pillow